export type Protopedia = {
  id: number;
  prototypeNm: string;
  licenseType: number;
  summary: string;
  videoUrl: string;
  status: number;
  systemDescription: string;
  freeComment: string;
  slideMode: number;
  teamNm: string;
  officialLink: string;
  relatedLink: string;
  relatedLink2: string;
  relatedLink3: string;
  relatedLink4: string;
  relatedLink5: string;
  releaseFlg: number;
  thanksFlg: number;
  mainUrl: string;
  viewCount: number;
  goodCount: number;
  commentCount: number;
  userNm: string;
  companyNm: string | null;
  materialNm: string | null;
  eventTitle: string | null;
  tags: string | null;
  image1: string;
  image2: string | null;
  image3: string | null;
  image4: string | null;
  image5: string | null;
  systemImage: string | null;
  releaseAt: string;
  createAt: string;
  updateAt: string;
  nid: string | null;
  uuid: string;
};
